[package]
name = "timely-viz"
version = "0.1.0"
authors = ["Chase Wilson <me@chasewilson.dev>"]
license = "MIT OR Apache-2.0"
edition = "2018"
default-run = "timely-viz"

[dependencies]
num = "0.3.1"
tera = "1.6.1"
anyhow = "1.0.38"
tracing = "0.1.25"
colorous = "1.0.3"
structopt = "0.3.21"
abomonation = "0.7.3"
sequence_trie = "0.3.6"
crossbeam-channel = "0.5.0"
abomonation_derive = "0.5.0"
tracing-subscriber = "0.2.16"
serde = { version = "1.0.123", features = ["derive"] }

[dependencies.differential-dataflow]
git = "https://github.com/TimelyDataflow/differential-dataflow"
default-features = false

[dependencies.timely]
git = "https://github.com/TimelyDataflow/timely-dataflow"
#default-features = false

[profile.dev]
debug = 0
lto = false
opt-level = 0
incremental = true

[profile.release]
debug = 2
lto = "fat"
opt-level = 3
codegen-units = 1
incremental = false
debug-assertions = false
