[package]
name = "ddshow"
description = "Timely and Differential dataflow log analysis and vizualization"
version = "0.1.1"
authors = ["Chase Wilson <me@chasewilson.dev>"]
license = "MIT OR Apache-2.0"
edition = "2018"
resolver = "2"
build = "build.rs"
repository = "https://github.com/Kixiron/ddshow"
keywords = ["timely", "differential", "dataflow", "tdiag"]
categories = [
    "command-line-interface",
    "command-line-utilities",
    "development-tools::debugging",
    "visualization",
]
default-run = "ddshow"

[workspace]
members = ["crates/*"]

[features]
default = []
timely-next = []

[dependencies]
num = "0.4.0"
tera = "1.6.1"
anyhow = "1.0.38"
tracing = "0.1.25"
colorous = "1.0.3"
bytecheck = "0.5.1"
byteorder = "1.4.3"
structopt = "0.3.21"
serde_json = "1.0.64"
abomonation = "0.7.3"
comfy-table = "3.0.0"
crossbeam-channel = "0.5.0"
abomonation_derive = "0.5.0"
tracing-subscriber = "0.2.16"
strum = { version = "0.21.0", features = ["derive"] }
serde = { version = "1.0.123", features = ["derive"] }
rkyv = { version = "0.6.6", features = ["validation"] }
tinyvec = { version = "1.2.0", features = ["alloc", "serde"] }
indicatif = { version = "0.16.2", features = ["improved_unicode"] }

ddshow-sink = { version = "0.1.1", path = "crates/ddshow-sink", features = ["ddflow", "tracing"] }
ddshow-types = { version = "0.1.1", path = "crates/ddshow-types", features = ["rkyv", "serde", "enable_abomonation"] }

timely = "0.12.0"
differential-dataflow = { version = "0.12.0", default-features = false }
# timely = { git = "https://github.com/TimelyDataflow/timely-dataflow" }
# differential-dataflow = { git = "https://github.com/TimelyDataflow/differential-dataflow" }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.0"

[build-dependencies.vergen]
version = "5.1.6"
default-features = false
features = ["build", "cargo", "rustc"]

[profile.dev]
debug = 0
lto = false
opt-level = 0
incremental = true

[profile.release]
debug = 0
lto = "thin"
opt-level = 3
codegen-units = 24
incremental = true
debug-assertions = false
