[package]
name = "ddshow"
version = "0.1.0"
authors = ["Chase Wilson <me@chasewilson.dev>"]
license = "MIT OR Apache-2.0"
edition = "2018"
resolver = "2"
build = "build.rs"
default-run = "ddshow"

[features]
default = []
timely-next = []

[dependencies]
num = "0.4.0"
tera = "1.6.1"
anyhow = "1.0.38"
tracing = "0.1.25"
colorous = "1.0.3"
structopt = "0.3.21"
serde_json = "1.0.64"
abomonation = "0.7.3"
comfy-table = "2.1.0"
crossbeam-channel = "0.5.0"
abomonation_derive = "0.5.0"
tracing-subscriber = "0.2.16"
strum = { version = "0.20.0", features = ["derive"] }
serde = { version = "1.0.123", features = ["derive"] }
tinyvec = { version = "1.2.0", features = ["alloc", "serde"] }

byteorder = "1.4.3"
bytecheck = "0.4.1"
rkyv = { version = "0.5.2", features = ["validation"] }

timely = "0.12.0"
differential-dataflow = "0.12.0"
# timely = { git = "https://github.com/TimelyDataflow/timely-dataflow" }
# differential-dataflow = { git = "https://github.com/TimelyDataflow/differential-dataflow" }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.0"

[build-dependencies.vergen]
version = "5.1.6"
default-features = false
features = ["build", "cargo", "git", "rustc"]

[profile.dev]
debug = 2
lto = false
opt-level = 0
incremental = true

[profile.release]
debug = 0
lto = "fat"
opt-level = 3
codegen-units = 1
incremental = false
debug-assertions = false
