[package]
name = "timely-viz-hook"
version = "0.1.0"
authors = ["Chase Wilson <me@chasewilson.dev>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies.timely]
git = "https://github.com/TimelyDataflow/timely-dataflow"
default-features = false
